# Generated by Django 5.1.4 on 2026-04-25 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('api_key_hash', models.CharField(db_index=True, help_text='SHA-256 hash kluczu API. Plaintext nie jest przechowywany.', max_length=128, unique=True)),
                ('iban', models.CharField(max_length=34)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_bank', models.ForeignKey(help_text='Bank w którym agent ma konto rozliczeniowe.', on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='banks.bank')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MSCAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('klik_fee_perc', models.DecimalField(decimal_places=2, help_text='Procent prowizji dla KLIK od kwoty brutto (np. 0.30 = 0.30%).', max_digits=5)),
                ('agent_fee_perc', models.DecimalField(decimal_places=2, help_text='Procent prowizji dla agenta od kwoty brutto (np. 1.00 = 1.00%).', max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, help_text='Null = bezterminowa.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msc_agreements', to='agents.agent')),
            ],
            options={
                'ordering': ['-valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='msc_valid_to_after_valid_from'), models.CheckConstraint(condition=models.Q(('klik_fee_perc__gte', 0), ('agent_fee_perc__gte', 0)), name='msc_fees_non_negative')],
            },
        ),
    ]
