# Generated by Django 5.1.4 on 2026-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='iban',
        ),
        migrations.AddField(
            model_name='agent',
            name='account_identifier',
            field=models.JSONField(default={}, help_text='Strukturalny identyfikator konta. Format zależy od strefy: IBAN dla PL/EU/UK, routing+account dla US. Schemat opisany w common.account.'),
            preserve_default=False,
        ),
    ]
