# Generated by Django 5.1.4 on 2026-04-25 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_remove_agent_iban_agent_account_identifier'),
        ('banks', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_snapshot', models.CharField(help_text='Kod KLIK użyty w transakcji. Audytowy — nie do lookupu.', max_length=6)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('klik_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Wyliczane przy /confirm.', max_digits=12, null=True)),
                ('agent_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('merchant_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], max_length=2)),
                ('is_on_us', models.BooleanField(help_text='True gdy sender_bank == merchant.settlement_bank.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('TIMEOUT', 'Timeout')], db_index=True, default='PENDING', max_length=20)),
                ('reject_reason', models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient funds'), ('USER_DECLINED', 'User declined'), ('PIN_FAILED', 'PIN authentication failed'), ('AML_BLOCK', 'AML compliance block'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='agents.agent')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='merchants.merchant')),
                ('sender_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_sender', to='banks.bank')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'zone'], name='codes_trans_status_8bd83d_idx'), models.Index(fields=['created_at'], name='codes_trans_created_10be27_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'idempotency_key'), name='tx_unique_agent_idempotency'), models.CheckConstraint(condition=models.Q(('amount_gross__gt', 0)), name='tx_amount_gross_positive')],
            },
        ),
    ]
