# Generated by Django 5.1.4 on 2026-04-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
