# Generated by Django 5.1.4 on 2026-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
