# Generated by Django 5.1.4 on 2026-06-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_transaction_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(blank=True, help_text='Internal client id po stronie banku nadawcy.', max_length=255),
        ),
    ]
