# Generated by Django 5.1.4 on 2026-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_transaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code_snapshot',
            field=models.CharField(help_text='Kod KLIK użyty w transakcji (6 cyfr C2B / 9 cyfr Cheque). Audytowy — nie do lookupu.', max_length=9),
        ),
    ]
