# Generated by Django 5.1.4 on 2026-04-25 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, help_text='Numer telefonu w formacie E.164 (np. +48501234567).', max_length=16, unique=True)),
                ('account_identifier', models.JSONField(help_text='Strukturalny identyfikator konta. Format zależy od strefy: IBAN dla PL/EU/UK ({"type": "iban", "value": "..."}), routing+account dla US. Schemat opisany w common.account.')),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], help_text='Strefa rejestracji aliasu. Musi być zgodna z prefiksem telefonu oraz strefą banku.', max_length=2)),
                ('bank', models.ForeignKey(help_text='Bank klienta — beneficjent przelewów P2P na ten numer.', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliasy',
                'ordering': ['phone'],
                'constraints': [models.UniqueConstraint(fields=('phone',), name='alias_phone_unique')],
            },
        ),
    ]
