services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev

  worker:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
    depends_on:
      rtgs-mock:
        condition: service_healthy

  beat:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
    depends_on:
      rtgs-mock:
        condition: service_healthy

  rtgs-mock:
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - ./rtgs_mock:/app
    ports:
      - "9000:9000"  # exposed dla łatwego curl-a z hosta

  bank-mock-backend:
    command: uvicorn main:app --host 0.0.0.0 --port 8100 --reload
    volumes:
      - ./bank_IO/backend:/app
    ports:
      - "8100:8100"   # webhook od KLIK + API dla UI

  bank-mock-frontend:
    ports:
      - "5174:5174"   # UI operatora

  agent:
    ports:
      - "5175:5175"
