services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev

  worker:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev

  beat:
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
