# Generated by Django 5.1.4 on 2026-04-25 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_identifier', models.JSONField(help_text='Strukturalny identyfikator konta. IBAN dla PL/EU/UK, routing+account dla US. Schemat w common.account.')),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_bank', models.ForeignKey(help_text='Bank w którym merchant ma konto rozliczeniowe.', on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='banks.bank')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
