# Generated by Django 5.1.4 on 2026-04-25 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa banku (unikalna w obrębie systemu).', max_length=128, unique=True)),
                ('api_key_hash', models.CharField(help_text='SHA-256 hash klucza API. Plaintext nie jest przechowywany.', max_length=64, unique=True)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], help_text='Strefa walutowo-krajowa, w której bank operuje.', max_length=2)),
                ('currency', models.CharField(choices=[('PLN', 'Złoty polski'), ('EUR', 'Euro'), ('GBP', 'Funt brytyjski'), ('USD', 'Dolar amerykański')], help_text='Waluta rozliczeniowa banku. Musi pasować do strefy.', max_length=3)),
                ('debt_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maksymalne saldo debetowe banku w sesji rozliczeniowej (w walucie banku). Przekroczenie wyklucza bank z sesji.', max_digits=18)),
                ('active', models.BooleanField(default=False, help_text='Czy bank może wywoływać API. False = onboarding niezakończony lub bank zablokowany ręcznie przez operatora.')),
                ('webhook_url', models.URLField(blank=True, default='', help_text='URL endpointu webhooka autoryzacyjnego banku. KLIK uderza tu z payloadem /authorize (patrz A3 w WORKFLOW.md).', max_length=500)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banki',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('currency', 'PLN'), ('zone', 'PL')), models.Q(('currency', 'EUR'), ('zone', 'EU')), models.Q(('currency', 'GBP'), ('zone', 'UK')), models.Q(('currency', 'USD'), ('zone', 'US')), _connector='OR'), name='bank_zone_currency_match'), models.CheckConstraint(condition=models.Q(('debt_limit__gte', 0)), name='bank_debt_limit_non_negative')],
            },
        ),
    ]
