# Generated by Django 5.1.4 on 2026-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='c2b_enabled',
            field=models.BooleanField(default=True, help_text='Czy bank uczestniczy w module C2B (płatności kodem). Wszystkie obecne banki domyślnie działają w C2B.'),
        ),
        migrations.AddField(
            model_name='bank',
            name='p2p_enabled',
            field=models.BooleanField(default=False, help_text='Czy bank uczestniczy w module P2P (przelewy po numerze telefonu). Aktywowane świadomie po podpisaniu warunków P2P i konfiguracji lookupu aliasów.'),
        ),
        migrations.AddField(
            model_name='bank',
            name='p2p_lookup_fee',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Opłata za pojedynczy lookup aliasu P2P (w walucie banku). Naliczana po stronie banku pytającego. 0 = bez opłaty.', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('p2p_lookup_fee__gte', 0)), name='bank_p2p_lookup_fee_non_negative'),
        ),
    ]
