# Generated by Django 5.1.4 on 2026-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_c2b_enabled_bank_p2p_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='webhook_url',
            field=models.CharField(blank=True, default='', help_text='URL endpointu webhooka autoryzacyjnego banku. KLIK uderza tu z payloadem /authorize (patrz A3 w WORKFLOW.md).', max_length=500),
        ),
    ]
