# Generated by Django 5.1.4 on 2026-06-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_webhook_url'),
        ('banks', '0004_bank_cheques_enabled_cheques_webhook_url'),
    ]

    operations = [
    ]
