# Generated by Django 5.1.4 on 2026-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_merge_20260603_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bic',
            field=models.CharField(blank=True, default='', help_text='Kod BIC/SWIFT banku. Wymagany dla strefy EU (TARGET identyfikuje banki po BIC). Dla pozostałych stref opcjonalny.', max_length=11),
        ),
        migrations.AddField(
            model_name='bank',
            name='settlement_iban',
            field=models.CharField(blank=True, default='', help_text='IBAN konta rozliczeniowego banku w RTGS. Wymagany dla strefy EU (TARGET wstawia go w DbtrAcct/CdtrAcct komunikatu ISO 20022).', max_length=34),
        ),
    ]
