# Generated by Django 5.1.4 on 2026-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_merge_20260603_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='recurring_enabled',
            field=models.BooleanField(default=False, help_text='Czy bank uczestniczy w module Recurring (zlecenia stałe). Wymaga też p2p_enabled=True (lookup aliasu jest mechanizmem P2P). Bank musi wystawiać endpointy /execute, /auto-paused, /cancelled.'),
        ),
        migrations.AddField(
            model_name='bank',
            name='recurring_webhook_url',
            field=models.URLField(blank=True, default='', help_text='URL bazowy dla webhooków modułu Recurring. KLIK uderza w {url}/execute, {url}/auto-paused i {url}/cancelled. Jeśli puste — fallback do webhook_url + "/recurring".', max_length=500),
        ),
    ]
