# Generated by Django 5.1.4 on 2026-06-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_bank_recurring_enabled_bank_recurring_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='cheques_webhook_url',
            field=models.CharField(blank=True, default='', help_text='URL bazowy dla webhooków modułu Cheques. KLIK uderza w {url}/redeemed i {url}/released. Jeśli puste — fallback do webhook_url + "/cheques".', max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='recurring_webhook_url',
            field=models.CharField(blank=True, default='', help_text='URL bazowy dla webhooków modułu Recurring. KLIK uderza w {url}/execute, {url}/auto-paused i {url}/cancelled. Jeśli puste — fallback do webhook_url + "/recurring".', max_length=500),
        ),
    ]
