# Generated by Django 5.1.4 on 2026-06-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_bank_bic_bank_settlement_iban'),
        ('banks', '0007_alter_bank_cheques_webhook_url_and_more'),
    ]

    operations = [
    ]
