# Generated by Django 5.1.4 on 2026-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_merge_20260614_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='fednow_account_number',
            field=models.CharField(blank=True, default='', help_text='Numer konta rozliczeniowego banku w FedNow (4-17 cyfr). Wstawiany do pacs.008 jako DbtrAcct/CdtrAcct. Analogia do pola settlement_iban dla TARGET2/EU.', max_length=17),
        ),
        migrations.AddField(
            model_name='bank',
            name='fednow_routing_number',
            field=models.CharField(blank=True, default='', help_text='ABA Routing Transit Number (RTN) banku w systemie FedNow. Dokładnie 9 cyfr. Wymagany dla strefy US przy settlement przez FedNow. Analogia do pola bic dla TARGET2/EU. Przykład: "021000021" (JPMorgan Chase).', max_length=9),
        ),
    ]
