# Generated by Django 5.1.4 on 2026-06-02 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_bank_c2b_enabled_bank_p2p_enabled_and_more'),
        ('codes', '0004_transaction_rejected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='9-cyfrowy kod czeku. Unikalny wśród ACTIVE (partial index).', max_length=9)),
                ('issuer_user_id', models.CharField(help_text='Wewnętrzny identyfikator klienta po stronie banku wystawcy.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota czeku. Niezmienna po wystawieniu.', max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], max_length=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywny'), ('REDEEMED', 'Zrealizowany'), ('CANCELLED', 'Anulowany'), ('EXPIRED', 'Wygasły')], db_index=True, default='ACTIVE', max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Idempotency-Key z POST /cheques/issue.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer_bank', models.ForeignKey(help_text='Bank który wystawił czek (wywołał /cheques/issue).', on_delete=django.db.models.deletion.PROTECT, related_name='issued_cheques', to='banks.bank')),
                ('transaction', models.OneToOneField(blank=True, help_text='Transakcja powstała przy realizacji czeku.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque', to='codes.transaction')),
            ],
            options={
                'verbose_name': 'Czek',
                'verbose_name_plural': 'Czeki',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='cheques_che_status_7989f6_idx'), models.Index(fields=['issuer_bank', 'status', '-created_at'], name='cheques_che_issuer__ea38af_idx'), models.Index(fields=['idempotency_key', 'issuer_bank'], name='cheques_che_idempot_5d29b9_idx')],
            },
        ),
    ]
