# Generated by Django 5.1.4 on 2026-06-12 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0006_bank_recurring_enabled_bank_recurring_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(help_text='Kiedy run miał być wykonany (= mandate.next_run_at w momencie dispatch).')),
                ('executed_at', models.DateTimeField(blank=True, help_text='Kiedy bank faktycznie wykonał przelew RTP (z odpowiedzi webhooka).', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Zaplanowany'), ('EXECUTING', 'W trakcie'), ('SUCCESS', 'Sukces'), ('FAILED', 'Nieudany'), ('SKIPPED', 'Pominięty')], db_index=True, default='SCHEDULED', max_length=10)),
                ('rtp_reference', models.CharField(blank=True, default='', help_text='ID przelewu RTP od banku (przy SUCCESS).', max_length=200)),
                ('failure_reason', models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Brak środków'), ('MANDATE_REVOKED_LOCALLY', 'Mandate odwołany w banku'), ('ACCOUNT_CLOSED', 'Konto zamknięte'), ('AML_BLOCK', 'Blokada AML'), ('RECIPIENT_ALIAS_GONE', 'Alias odbiorcy usunięty'), ('NETWORK_TIMEOUT', 'Timeout sieci do banku'), ('OTHER', 'Inny')], default='', help_text='Wypełniany przy FAILED. Pusty dla SKIPPED (nie liczy się do auto-pause).', max_length=30)),
                ('lookup_response_snapshot', models.JSONField(blank=True, help_text='Dane aliasu odbiorcy z lookupu w momencie execution (audit).', null=True)),
            ],
            options={
                'verbose_name': 'Wykonanie zlecenia',
                'verbose_name_plural': 'Wykonania zleceń',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_user_id', models.CharField(help_text='Wewnętrzny identyfikator klienta po stronie banku nadawcy.', max_length=200)),
                ('recipient_phone', models.CharField(help_text='Alias odbiorcy w E.164. Świadomie bez FK do Alias (patrz docstring modułu).', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Stała kwota pojedynczego przelewu. Niezmienna po utworzeniu.', max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], max_length=2)),
                ('cycle', models.CharField(choices=[('DAILY', 'Codziennie'), ('WEEKLY', 'Co tydzień'), ('MONTHLY', 'Co miesiąc')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='NULL = mandate open-ended (bez daty końcowej).', null=True)),
                ('next_run_at', models.DateTimeField(help_text='Czas najbliższego runu. Kalkulowany z cycle, zakotwiczony w start_date.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywny'), ('PAUSED', 'Wstrzymany'), ('CANCELLED', 'Anulowany'), ('COMPLETED', 'Zakończony')], db_index=True, default='ACTIVE', max_length=10)),
                ('failed_runs_count', models.PositiveIntegerField(default=0, help_text='Licznik failów Z RZĘDU. Reset przy SUCCESS oraz przy resume.')),
                ('mandate_signed_at', models.DateTimeField(help_text='Pole audytowe z payloadu /create — kiedy klient podpisał PIN-em. KLIK ufa bankowi.')),
                ('idempotency_key', models.CharField(help_text='Idempotency-Key z POST /recurring/create.', max_length=64)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_execution', models.ForeignKey(blank=True, help_text='Ostatnia zakończona execution (SUCCESS).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recurring.recurringexecution')),
                ('payer_bank', models.ForeignKey(help_text='Bank nadawcy — właściciel mandate (wywołał /recurring/create).', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transfers', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Zlecenie stałe',
                'verbose_name_plural': 'Zlecenia stałe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recurringexecution',
            name='recurring_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='recurring.recurringtransfer'),
        ),
        migrations.AddIndex(
            model_name='recurringtransfer',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['next_run_at'], name='recurring_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransfer',
            index=models.Index(fields=['payer_bank', 'payer_user_id', 'status'], name='recurring_payer_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransfer',
            constraint=models.UniqueConstraint(fields=('idempotency_key', 'payer_bank'), name='recurring_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(fields=['recurring_transfer', '-scheduled_for'], name='recurring_exec_mandate_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(condition=models.Q(('status', 'SCHEDULED')), fields=['status'], name='recurring_exec_scheduled_idx'),
        ),
    ]
