# Generated by Django 5.1.4 on 2026-04-27 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_bank_c2b_enabled_bank_p2p_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], db_index=True, max_length=2)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('NETTING', 'Netting'), ('SETTLING', 'Settling'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='OPEN', max_length=20)),
                ('total_entries_count', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, help_text='Suma kwot brutto wszystkich entries w sesji.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['zone', 'status', 'started_at'], name='ledger_sett_zone_1cc4cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_type', models.CharField(choices=[('BANK', 'Bank'), ('KLIK', 'KLIK'), ('AGENT', 'Agent')], max_length=10)),
                ('beneficiary_ref', models.UUIDField(blank=True, help_text='Bank.id lub Agent.id; null gdy beneficiary_type=KLIK.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('zone', models.CharField(choices=[('PL', 'Polska (SORBNET3)'), ('EU', 'Strefa Euro (TARGET2)'), ('UK', 'Wielka Brytania (CHAPS)'), ('US', 'Stany Zjednoczone (FedNow)')], db_index=True, max_length=2)),
                ('entry_type', models.CharField(choices=[('MERCHANT_NET', 'Merchant net'), ('KLIK_FEE_C2B', 'KLIK fee (C2B)'), ('AGENT_FEE', 'Agent fee'), ('BANK_TO_BANK', 'Bank to bank (off-us merchant_net)'), ('P2P_LOOKUP_FEE', 'KLIK fee (P2P lookup)')], max_length=20)),
                ('source_ref', models.CharField(db_index=True, help_text='idempotency_key transakcji C2B lub id agregacji P2P. Klucz idempotency dla record_*.', max_length=100)),
                ('settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_bank', models.ForeignKey(help_text='Bank-dłużnik (płaci przez RTGS).', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_from', to='banks.bank')),
                ('to_bank', models.ForeignKey(help_text='Bank fizycznie otrzymujący środki (gdzie KLIK/agent ma konto).', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_to', to='banks.bank')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.settlementsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zone', 'settled', 'created_at'], name='ledger_ledg_zone_939f78_idx'), models.Index(fields=['source_ref'], name='ledger_ledg_source__345aa7_idx'), models.Index(fields=['session', 'settled'], name='ledger_ledg_session_7b6c5e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('beneficiary_ref__isnull', True), ('beneficiary_type', 'KLIK')), models.Q(models.Q(('beneficiary_type', 'KLIK'), _negated=True), ('beneficiary_ref__isnull', False)), _connector='OR'), name='ledger_beneficiary_consistency'), models.CheckConstraint(condition=models.Q(models.Q(('settled', False), ('settled_at__isnull', True)), models.Q(('settled', True), ('settled_at__isnull', False)), _connector='OR'), name='ledger_settled_at_consistency')],
            },
        ),
        migrations.CreateModel(
            name='SettlementTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('rtgs_reference', models.CharField(blank=True, help_text='Identyfikator zwrócony przez RTGS po dispatch.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_transfers_from', to='banks.bank')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ledger.settlementsession')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_transfers_to', to='banks.bank')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='ledger_sett_session_1d9f12_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_amount_positive'), models.CheckConstraint(condition=models.Q(('from_bank', models.F('to_bank')), _negated=True), name='transfer_from_to_different')],
            },
        ),
    ]
