# Generated by Django 5.1.4 on 2026-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransfer',
            name='failure_reason',
            field=models.CharField(blank=True, default='', help_text='Powód odrzucenia transferu prezez RTGS (wypełniany przy statusie FAILED).', max_length=255),
        ),
    ]
